export let notesData = [
  {
    id: '1',
    title: "Title 1",
    content: "This is the content of note 1.",
    tags: ["Work", "Important"],
    lastModified: "2:00 pm",
    pinned: false,
  },
  {
    id: '2',
    title: "Title 2",
    content: "This is the content of note 2.",
    tags: ["Personal", "Reminder"],
    lastModified: "13 Oct",
    pinned: false,
  },
  {
    id: "3",
    title: "Title 3",
    content: "This is the content of note 3.",
    tags: ["Shopping", "Urgent"],
    lastModified: "11 Oct",
    pinned: true,
  },
  {
    id: "4",
    title: "Title 4",
    content: "This is the content of note 4.",
    tags: ["Work", "Reminder"],
    lastModified: "13 Aug",
    pinned: false,
  },
  {
    id: '5',
    title: "Title 5",
    content: "This is the content of note 5.",
    tags: ["Personal", "Urgent"],
    lastModified: "31 July 2022",
    pinned: false,
  },
  {
    id: '6',
    title: "Title 6",
    content: "This is the content of note 6.",
    tags: ["Shopping", "Important"],
    lastModified: "31 July 2022",
    pinned: false,
  },
  {
    id: '7',
    title: "Title 7",
    content: "This is the content of note 7.",
    tags: ["Work", "Urgent"],
    lastModified: "5 June 2022",
    pinned: false,
  },
  {
    id: '8',
    title: "Title 8",
    content: "This is the content of note 8.",
    tags: ["Personal", "Important"],
    lastModified: "18 Sept 2021",
    pinned: false,
  }
];
