export const tasks = [
  {
    id: "xO1Fya341",
    sectionId: "xya341",
    name: "Task 1",
    priority: 0,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya342",
    name: "Task 2",
    sectionId: "xya341",
    priority: 1,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya343",
    name: "Task 3",
    sectionId: "xya341",
    priority: 2,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya349",
    name: "Task 9",
    sectionId: "xya341",
    priority: 0,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya344",
    name: "Task 4",
    sectionId: "xya342",
    priority: 1,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya345",
    name: "Task 5",
    sectionId: "xya342",
    priority: 2,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya346",
    name: "Task 6",
    sectionId: "xya343",
    priority: 0,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya347",
    name: "Task 7",
    sectionId: "xya344",
    priority: 1,
    tags: ["tag1", "tag2"],
  },
  {
    id: "xO1Fya348",
    name: "Task 8",
    sectionId: "xya345",
    priority: 2,
    tags: ["tag1", "tag2"],
  }
];
